import streamlit as st
from PIL import Image
import google.generativeai as genai  # Google Generative AI Python SDK that contains methods and classes to interact with Google's generative AI models.

# ---------------------------------------------------
# 1. Initialize Environment (No direct action needed for Streamlit Secrets)
# ---------------------------------------------------

# Quick Note on Inspiration:
# Inspired by the need to provide users with expert photo critiques using advanced AI models,
# enhancing photography skills through constructive feedback.

# ---------------------------------------------------
# 2. Configure API Key using Streamlit Secrets
# ---------------------------------------------------

# Access the API key from Streamlit secrets
try:
    api_key = st.secrets["API_KEY"]
    if not api_key:
        st.error("Google API key not found in Streamlit Secrets! Please add it to the Secrets section of your app.")
        st.stop()
    # Configure Google Generative AI SDK with the API key
    genai.configure(api_key=api_key)
except KeyError:
    st.error("Google API key not found in Streamlit Secrets! Please add a secret named 'API_KEY' with your key.")
    st.stop()

# ---------------------------------------------------
# 3. Initialize Generative Model & Define Functions
# ---------------------------------------------------

# Initialize the Generative Model
model = genai.GenerativeModel("gemini-2.0-flash")  # Initializes an instance of the GenerativeModel class from the genai SDK

def get_gemini_response(input_prompt, image):
    """
    Sends the input prompt and image data to Gemini and retrieves the response.
    
    Args:
        input_prompt (str): The prompt instructing the AI on how to critique the photo.
        image (list): A list containing image data prepared for the API call.
    
    Returns:
        str: The text response generated by the AI model.
    """
    response = model.generate_content([input_prompt, image[0]])
    return response.text

def get_image_content(uploaded_file):
    """
    Processes the uploaded image file and prepares it for the API call.
    
    Args:
        uploaded_file (UploadedFile): The image file uploaded by the user.
    
    Returns:
        list: A list of dictionaries containing MIME type and image data.
    
    Raises:
        FileNotFoundError: If no file is uploaded.
    """
    if uploaded_file is not None:
        image_byte_data = uploaded_file.getvalue()
        image_parts = [{
            "mime_type": uploaded_file.type,
            "data": image_byte_data
        }]
        return image_parts
    else:
        raise FileNotFoundError("File not uploaded")

# ---------------------------------------------------
# 4. Streamlit Interface Setup
# ---------------------------------------------------

# Configure Streamlit Page
st.set_page_config(page_title="", layout="centered")

# Display App Title
# st.markdown("<h1 style='text-align: center;'>PhotoCritique App</h1>", unsafe_allow_html=True)

# Optional: Additional Inputs (Scene Type, Desired Feedback, etc.)
# For simplicity, we'll keep only the image upload in this example.

# Set Up Image Upload Interface
uploaded_file = st.file_uploader("Upload Your Photo to Receive AI-Powered Critique", type=["jpg", "png", "jpeg"])
if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="", use_container_width=True)

# ---------------------------------------------------
# 5. User Interaction & Generate Critique
# ---------------------------------------------------

# Submit Button to Generate Critique
submit = st.button("Press Button to Receive Critique")

# Sprachwahl-Schaltfläche neben dem Button hinzufügen
col1, col2 = st.columns([3, 2])

with col1:
    # Sprachwahl-Schalte
    language = st.radio(
        "Select Language", 
        ["English", "German", "Spanish", "French"], 
        index=0
    )

with col2:
    # Submit Button
    submit = st.button("Press Button to Receive Critique")

# Definieren Sie den Critique Prompt basierend auf der ausgewählten Sprache
if language == "English":
    input_prompt = """
    Provide a constructive and detailed photographic critique, offering specific feedback and suggestions for improvement on the following aspects:\n\n
                "- Composition: Analyze ...\n"
                "- Lighting: Evaluate ...\n"
                "- Focus and Sharpness: Assess ...\n"
                "- Exposure: Determine ...\n"
                "- Color Balance: Examine ...\n"
                "- Creativity and Impact: Consider ...\n\n"
                "Begin your critique with a positive two-sentence summary ...\n\n"
                "Structure your detailed feedback into two distinct sections:\n\n"
                "**Positive Critique:** one sentence per aspect...\n\n"
                "**Recommended Optimizations:** one sentence per aspect...\n\n"
                "Conclude your critique with an overall rating of the photo on a scale of 1 to 10 and a short explanation, where 10 represents the highest possible score.
                Please use an upbeat, chipper tone."
    """
elif language == "German":
    input_prompt = """
    Bitte geben Sie eine konstruktive und detaillierte fotografische Kritik ab, indem Sie spezifisches Feedback und Verbesserungsvorschläge zu den folgenden Aspekten machen:\n\n
                "- Komposition: Analysieren Sie ...\n"
                "- Beleuchtung: Bewerten Sie ...\n"
                "- Fokus und Schärfe: Beurteilen Sie ...\n"
                "- Belichtung: Bestimmen Sie ...\n"
                "- Farbgleichgewicht: Untersuchen Sie ...\n"
                "- Kreativität und Wirkung: Berücksichtigen Sie ...\n\n"
                "Beginnen Sie Ihre Kritik mit einer positiven zweisätzigen Zusammenfassung ...\n\n"
                "Strukturieren Sie Ihr detailliertes Feedback in zwei separate Abschnitte:\n\n"
                "**Positive Kritik:** ein Satz pro Aspekt...\n\n"
                "**Empfohlene Optimierungen:** ein Satz pro Aspekt...\n\n"
                "Schließen Sie Ihre Kritik mit einer Gesamtbewertung des Fotos auf einer Skala von 1 bis 10 und einer kurzen Erklärung ab, wobei 10 die höchstmögliche Punktzahl darstellt.
                Bitte verwenden Sie einen aufmunternden, fröhlichen Ton."
    """
elif language == "Spanish":
    input_prompt = """
    Proporcione una crítica fotográfica constructiva y detallada, ofreciendo comentarios específicos y sugerencias de mejora sobre los siguientes aspectos:\n\n
                "- Composición: Analice ...\n"
                "- Iluminación: Evalúe ...\n"
                "- Enfoque y nitidez: Evalúe ...\n"
                "- Exposición: Determine ...\n"
                "- Balance de colores: Examine ...\n"
                "- Creatividad e impacto: Considere ...\n\n"
                "Comience su crítica con un resumen positivo de dos oraciones ...\n\n"
                "Estructure sus comentarios detallados en dos secciones distintas:\n\n"
                "**Crítica Positiva:** una oración por aspecto...\n\n"
                "**Optimización Recomendada:** una oración por aspecto...\n\n"
                "Concluya su crítica con una calificación general de la foto en una escala de 1 a 10 y una breve explicación, donde 10 representa la puntuación más alta posible.
                Use un tono alegre y optimista."
    """
elif language == "French":
    input_prompt = """
    Fournissez une critique photographique constructive et détaillée, en offrant des commentaires spécifiques et des suggestions d'amélioration sur les aspects suivants :\n\n
                "- Composition : Analysez ...\n"
                "- Éclairage : Évaluez ...\n"
                "- Mise au point et netteté : Évaluez ...\n"
                "- Exposition : Déterminez ...\n"
                "- Balance des couleurs : Examinez ...\n"
                "- Créativité et impact : Considérez ...\n\n"
                "Commencez votre critique par un résumé positif de deux phrases ...\n\n"
                "Structurez vos commentaires détaillés en deux sections distinctes :\n\n"
                "**Critique positive :** une phrase par aspect...\n\n"
                "**Optimisations recommandées :** une phrase par aspect...\n\n"
                "Concluez votre critique par une note globale de la photo sur une échelle de 1 à 10 et une courte explication, où 10 représente la note la plus élevée possible.
                Utilisez un ton joyeux et optimiste."
    """

# Der restliche Code bleibt unverändert.
if submit:
    try:
        # Handle Image Upload and Display
        image_data = get_image_content(uploaded_file)
        
        # Generate Critique basierend auf der Sprachwahl
        response = get_gemini_response(input_prompt, image_data)
        
        # Display AI-Generated Critique
        st.subheader("Photo Critique")
        st.write(response)
    except FileNotFoundError as e:
        # Manage Errors: File Not Uploaded
        st.error(str(e))
    except Exception as e:
        # Manage Errors: Other Exceptions
        st.error(f"An error occurred: {e}")
        st.error(f"An error occurred: {e}")
